baseURL = 'https://theus7b.github.io/'
languageCode = 'pt-BR'
title = 'theus7b'
disableKinds = ['taxonomy', 'term', 'section']

[params]
description = 'Um canto pessoal na internet para escrever sobre computadores, programação, Linux e o que mais der vontade.'
